name: cd

on:
  push:
    branches: [ main ]

jobs:
  docker-image:
    env:
      IMAGE: test/pvs-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build docker image
        run: mvn spring-boot:build-image -B -Dspring-boot.build-image.imageName=${{ env.IMAGE }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: docker push ${{ env.IMAGE }}
